import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import ReductionBanner from "./features/ReductionBanner";
import Header from "./features/Header";
import Footer from "./features/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
        <body className={cn(inter.className,"flex w-full  flex-col items-center justify-center")}>
        <ReductionBanner/>
        <Header/>
        {children}
        </body>
    </html>
  );
}
